---
title: "Results: Active Layer Thickness"
output: html_document
editor_options: 
  chunk_output_type: console
---

<style type="text/css">
.main-container {
  max-width: 1400px;
  margin-left: auto;
  margin-right: auto;
}
</style>


<details>
  <summary>R Library</summary>
  ```{r libraries, message=FALSE, warning=FALSE,  results=FALSE}
  library(readxl)
  library(ncdf4)
  library(raster)
  library(tidyverse)
  library(ggforce)
  library(grid)
  library(mgcv)
  library(sf)
  sf::sf_use_s2(FALSE)
  ```
</details><br/> 

```{r include = FALSE, results = FALSE}
  load("data/inSitu_alt.rda")
  
  ## base map
  mp <-  st_read("~/Google Drive/GeoDat/NaturalEarth/50m_physical/ne_50m_land/ne_50m_land.shp", quiet = TRUE) %>% 
    st_set_crs(4326) %>% st_buffer(0) %>% st_union() %>%
    st_sym_difference(st_read("~/Google Drive/GeoDat/NaturalEarth/110m_physical/ne_110m_lakes/ne_110m_lakes.shp", quiet = TRUE) %>% 
                        st_set_crs(4326) %>% st_union()) %>%
    st_transform("+proj=stere +lat_0=90 +lat_ts=71 +lon_0=0 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs") %>%
    st_crop(st_bbox(c(xmin = -5.5e6, ymin = -4e6, xmax = 8e6, ymax = 4e6)))
  
  map <- ggplot() +
    geom_sf(data = mp, colour = NA, fill = "slategray2") +
    theme_bw() +
    xlim(-5e6, 7.5e6) + ylim(-3.8e6, 3.8e6)
  
  # rast <- raster("~/Documents/ESAproject/SimulationData/PermafrostExtent/ESACCI-PERMAFROST-L4-PFR-MODISLST_CRYOGRID-AREA4_PP-2018-fv03.0.nc")
  # rast_spdf <- as(aggregate(rast, 15), "SpatialPixelsDataFrame")
  # rast_df   <- as.data.frame(rast_spdf)
  # colnames(rast_df) <- c("value", "x", "y")
  # save(rast_df, file = "Rmarkdown/temp/rast_df.rda")
  load("data/temp/rast_df.rda")
```

